/**
 * VoyageX — Central Destination Dataset
 * Rich dataset covering India and International destinations.
 * Structured for fast client-side querying, filtering, and trip planning.
 */

const DESTINATIONS = [
  // --- INDIA DESTINATIONS ---
  {
    id: "manali",
    name: "Manali",
    country: "India",
    region: "India",
    category: "Mountains",
    budgetTier: "Budget",
    avgDailyCostINR: 2800,
    avgDailyCostUSD: 34,
    rating: 4.8,
    reviews: 1420,
    duration: "4-5 Days",
    bestTime: "October - June",
    description: "Nestled in the Beas River valley, Manali offers breathtaking snow-capped Himalayan peaks, adventure sports, pine forests, and vibrant cafes in Old Manali.",
    highlights: ["Solang Valley Adventure", "Rohtang Pass Snow", "Old Manali Cafes", "Jogini Waterfall Trek"],
    attractions: ["Hadimba Temple", "Solang Valley", "Rohtang Pass", "Vashisht Hot Springs", "Manu Temple"],
    foodMustTry: ["Siddu (Steamed Bread)", "Trout Fish", "Thukpa & Momos", "Kullu Dham"],
    activities: ["Paragliding", "River Rafting", "Trekking", "Skiing", "Cafe Hopping"],
    weatherSample: { temp: "14°C", condition: "Pleasant & Breezy", icon: "🌤️", rainChance: "15%" },
    lat: 32.2396,
    lng: 77.1887,
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "goa",
    name: "Goa",
    country: "India",
    region: "India",
    category: "Beach",
    budgetTier: "Standard",
    avgDailyCostINR: 3500,
    avgDailyCostUSD: 42,
    rating: 4.7,
    reviews: 2180,
    duration: "3-5 Days",
    bestTime: "November - March",
    description: "India's coastal paradise blends sun-drenched Arabian Sea beaches, Portuguese colonial architecture, pulsating nightlife, and delectable coastal seafood.",
    highlights: ["Palolem & Vagator Sunsets", "Fort Aguada Views", "Fontainhas Latin Quarter", "Beach Shacks & Night Markets"],
    attractions: ["Basilica of Bom Jesus", "Dudhsagar Waterfalls", "Anjuna Flea Market", "Chapora Fort"],
    foodMustTry: ["Goan Fish Curry", "Pork Vindaloo", "Bebinca", "Prawn Balchão"],
    activities: ["Scuba Diving", "Sunset Cruises", "Scooter Exploration", "Water Sports", "Heritage Walks"],
    weatherSample: { temp: "29°C", condition: "Sunny & Tropical", icon: "☀️", rainChance: "5%" },
    lat: 15.2993,
    lng: 74.1240,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "jaipur",
    name: "Jaipur",
    country: "India",
    region: "India",
    category: "Culture",
    budgetTier: "Standard",
    avgDailyCostINR: 3200,
    avgDailyCostUSD: 38,
    rating: 4.8,
    reviews: 1890,
    duration: "3-4 Days",
    bestTime: "October - March",
    description: "The Pink City of Rajasthan mesmerizes travelers with grand hilltop fortresses, opulent royal palaces, vibrant bazaars, and legendary Rajput hospitality.",
    highlights: ["Amber Fort Elephant Passage", "Hawa Mahal Facade", "City Palace Museum", "Nahargarh Sunset Point"],
    attractions: ["Amber Fort", "Hawa Mahal", "Jantar Mantar", "Jal Mahal", "Albert Hall Museum"],
    foodMustTry: ["Dal Baati Churma", "Pyaaz Kachori", "Ghewar", "Laal Maas"],
    activities: ["Heritage Walking Tours", "Hot Air Ballooning", "Block Print Shopping", "Photography"],
    weatherSample: { temp: "26°C", condition: "Clear Skies", icon: "☀️", rainChance: "0%" },
    lat: 26.9124,
    lng: 75.7873,
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: true
  },
  {
    id: "kashmir",
    name: "Kashmir Valley",
    country: "India",
    region: "India",
    category: "Nature",
    budgetTier: "Standard",
    avgDailyCostINR: 4200,
    avgDailyCostUSD: 50,
    rating: 4.9,
    reviews: 1650,
    duration: "5-7 Days",
    bestTime: "April - October (Spring/Autumn) & Dec-Feb (Snow)",
    description: "Often heralded as 'Paradise on Earth', Kashmir enchants with tranquil Dal Lake houseboats, saffron meadows in Pampore, and alpine glaciers in Gulmarg.",
    highlights: ["Shikara Ride on Dal Lake", "Gulmarg Gondola Ride", "Pahalgam Betaab Valley", "Sonamarg Glaciers"],
    attractions: ["Dal Lake", "Mughal Gardens", "Gulmarg Meadow", "Aru Valley", "Shankaracharya Temple"],
    foodMustTry: ["Rogan Josh", "Kahwa Tea", "Dum Aloo", "Gushtaba (Wazwan)"],
    activities: ["Gondola Skiing", "Houseboat Stays", "Shikara Photography", "Trout Fishing", "Pony Treks"],
    weatherSample: { temp: "12°C", condition: "Crisp Mountain Air", icon: "🏔️", rainChance: "20%" },
    lat: 34.0837,
    lng: 74.7973,
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: false
  },
  {
    id: "kerala",
    name: "Kerala (Alleppey & Munnar)",
    country: "India",
    region: "India",
    category: "Nature",
    budgetTier: "Standard",
    avgDailyCostINR: 3600,
    avgDailyCostUSD: 43,
    rating: 4.9,
    reviews: 2340,
    duration: "5-6 Days",
    bestTime: "September - March",
    description: "God's Own Country presents tranquil emerald backwaters, sprawling aromatic tea estates in Munnar, Ayurvedic healing retreats, and palm-fringed coastlines.",
    highlights: ["Overnight Houseboat Cruise", "Tea Garden Walks", "Kathakali Performance", "Ayurvedic Spa Treatments"],
    attractions: ["Vembanad Lake", "Eravikulam National Park", "Mattupetty Dam", "Marari Beach"],
    foodMustTry: ["Appam with Stew", "Kerala Sadya", "Karimeen Pollichathu", "Banana Fritters"],
    activities: ["Backwater Kayaking", "Tea Tasting", "Bird Watching", "Ayurveda Wellness", "Spice Plantation Tours"],
    weatherSample: { temp: "27°C", condition: "Tropical Warmth", icon: "🌴", rainChance: "10%" },
    lat: 9.4981,
    lng: 76.3388,
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: false
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    country: "India",
    region: "India",
    category: "Adventure",
    budgetTier: "Budget",
    avgDailyCostINR: 2200,
    avgDailyCostUSD: 26,
    rating: 4.7,
    reviews: 1510,
    duration: "3-4 Days",
    bestTime: "September - May",
    description: "The Yoga Capital of the World along the holy Ganges, where adrenaline-pumping white water rapids meet spiritual evening aartis and serene ashrams.",
    highlights: ["Triveni Ghat Evening Aarti", "Ganges River Rafting Grade III/IV", "Beatles Ashram Graffiti", "Suspension Bridges"],
    attractions: ["Ram Jhula & Laxman Jhula", "Beatles Ashram", "Neer Garh Waterfall", "Parmarth Niketan"],
    foodMustTry: ["Ayurvedic Thali", "Masala Chai", "Falafel & Hummus", "Wood-fired Pizza"],
    activities: ["White Water Rafting", "Bungee Jumping", "Yoga & Meditation", "Cliff Jumping", "Camping"],
    weatherSample: { temp: "24°C", condition: "Gentle Breeze", icon: "🌤️", rainChance: "5%" },
    lat: 30.0869,
    lng: 78.2676,
    image: "https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: true
  },
  {
    id: "ladakh",
    name: "Ladakh (Leh)",
    country: "India",
    region: "India",
    category: "Adventure",
    budgetTier: "Standard",
    avgDailyCostINR: 4500,
    avgDailyCostUSD: 54,
    rating: 4.9,
    reviews: 1780,
    duration: "6-8 Days",
    bestTime: "May - September",
    description: "High altitude desert of stark moonscapes, surreal cobalt Pangong Tso lake, ancient Tibetan Buddhist monasteries, and high mountain passes.",
    highlights: ["Pangong Lake Color Shifts", "Khardung La Pass (17,582 ft)", "Nubra Valley Sand Dunes", "Magnetic Hill"],
    attractions: ["Thiksey Monastery", "Pangong Tso", "Nubra Valley", "Shanti Stupa", "Hemis National Park"],
    foodMustTry: ["Skyu (Traditional Stew)", "Butter Tea", "Momos & Tingmo", "Chhurpi (Yak Cheese)"],
    activities: ["Motorbike Road Trips", "Stargazing at Hanle", "Double-humped Camel Ride", "Monastery Meditation"],
    weatherSample: { temp: "10°C", condition: "Dry & Sunny", icon: "☀️", rainChance: "0%" },
    lat: 34.1526,
    lng: 77.5771,
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "udaipur",
    name: "Udaipur",
    country: "India",
    region: "India",
    category: "Luxury",
    budgetTier: "Luxury",
    avgDailyCostINR: 5800,
    avgDailyCostUSD: 70,
    rating: 4.8,
    reviews: 1430,
    duration: "3-4 Days",
    bestTime: "October - March",
    description: "The City of Lakes and Venice of the East, famed for shimmering Lake Pichola, floating white marble palaces, vintage car collections, and romantic sunsets.",
    highlights: ["Lake Pichola Sunset Boat Ride", "City Palace Architecture", "Bagore Ki Haveli Folk Dance", "Jagmandir Island"],
    attractions: ["City Palace", "Lake Pichola", "Jagdish Temple", "Saheliyon-ki-Bari", "Monsoon Palace"],
    foodMustTry: ["Rajasthani Ker Sangri", "Mirchi Vada", "Rabri", "Kachori"],
    activities: ["Lake Cruising", "Palace Tours", "Rooftop Romantic Dinners", "Miniature Painting Workshops"],
    weatherSample: { temp: "25°C", condition: "Warm & Clear", icon: "☀️", rainChance: "0%" },
    lat: 24.5854,
    lng: 73.7125,
    image: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: false
  },

  // --- INTERNATIONAL DESTINATIONS ---
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "International",
    category: "Beach",
    budgetTier: "Standard",
    avgDailyCostINR: 5200,
    avgDailyCostUSD: 62,
    rating: 4.9,
    reviews: 3200,
    duration: "6-8 Days",
    bestTime: "April - October",
    description: "The Island of the Gods combines exotic volcanic peaks, cascading rice terraces in Ubud, cliffside sea temples in Uluwatu, and world-class surfing beaches.",
    highlights: ["Tegallalang Rice Terraces", "Uluwatu Cliffside Kecak Dance", "Nusa Penida Day Trip", "Ubud Sacred Monkey Forest"],
    attractions: ["Tanah Lot Temple", "Mount Batur", "Uluwatu Temple", "Seminyak Beach", "Tirta Empul"],
    foodMustTry: ["Nasi Goreng", "Babi Guling", "Satay Lilit", "Pisang Goreng"],
    activities: ["Surfing Lessons", "Sunrise Volcano Trek", "Balinese Cooking Class", "Beach Club Lounging"],
    weatherSample: { temp: "28°C", condition: "Tropical Breeze", icon: "⛅", rainChance: "15%" },
    lat: -8.4095,
    lng: 115.1889,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    region: "International",
    category: "Culture",
    budgetTier: "Luxury",
    avgDailyCostINR: 14500,
    avgDailyCostUSD: 175,
    rating: 4.8,
    reviews: 4120,
    duration: "4-6 Days",
    bestTime: "May - September",
    description: "The City of Light captivates with world-renowned art museums, grand Haussmann boulevards, iconic Eiffel Tower panoramas, and bohemian sidewalk cafes.",
    highlights: ["Eiffel Tower Sparkling at Night", "Louvre Mona Lisa & Glass Pyramid", "Seine River Dinner Cruise", "Montmartre & Sacré-Cœur"],
    attractions: ["Eiffel Tower", "Louvre Museum", "Musée d'Orsay", "Notre-Dame Cathedral", "Arc de Triomphe"],
    foodMustTry: ["Warm Butter Croissant", "Escargots", "Duck Confit", "French Macarons", "Crêpes"],
    activities: ["Museum Hopping", "Boutique Shopping on Le Marais", "Wine & Cheese Tasting", "Seine Cycling"],
    weatherSample: { temp: "19°C", condition: "Partly Cloudy", icon: "⛅", rainChance: "25%" },
    lat: 48.8566,
    lng: 2.3522,
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    region: "International",
    category: "City",
    budgetTier: "Standard",
    avgDailyCostINR: 11000,
    avgDailyCostUSD: 132,
    rating: 4.9,
    reviews: 3890,
    duration: "5-7 Days",
    bestTime: "March - May & September - November",
    description: "A dizzying hyper-modern metropolis harmonized with centuries-old Shinto shrines, neon-lit Akihabara tech alleys, Michelin-star ramen, and seamless bullet trains.",
    highlights: ["Shibuya Crossing Scramble", "teamLab Borderless Digital Art", "Senso-ji Temple Lanterns", "Shinjuku Skyscraper Views"],
    attractions: ["Shibuya Sky", "Senso-ji Temple", "Meiji Jingu Shrine", "Tsukiji Outer Market", "Tokyo Skytree"],
    foodMustTry: ["Tonkotsu Ramen", "Fresh Edomae Sushi", "Wagyu Beef Skewers", "Matcha Parfait"],
    activities: ["Sushi Making Class", "Akihabara Gaming", "Karaoke Box Night", "Ghibli Museum Visit"],
    weatherSample: { temp: "18°C", condition: "Mild & Sunny", icon: "🌤️", rainChance: "10%" },
    lat: 35.6762,
    lng: 139.6503,
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "International",
    category: "Luxury",
    budgetTier: "Luxury",
    avgDailyCostINR: 12500,
    avgDailyCostUSD: 150,
    rating: 4.7,
    reviews: 2950,
    duration: "4-5 Days",
    bestTime: "November - April",
    description: "Futuristic desert skyline boasting the world's tallest tower, artificial archipelago islands, ultra-luxury shopping malls, and thrilling dune bashing safaris.",
    highlights: ["Burj Khalifa 148th Floor Deck", "Desert Safari BBQ & Dune Bashing", "Dubai Mall Fountain Show", "Palm Jumeirah Boardwalk"],
    attractions: ["Burj Khalifa", "The Dubai Mall", "Museum of the Future", "Dubai Frame", "Miracle Garden"],
    foodMustTry: ["Shawarma", "Al Harees", "Kunafa", "Luqaimat with Date Syrup"],
    activities: ["Dune Bashing", "Skydive Dubai", "Yacht Cruise Marina", "Gold Souk Bargaining"],
    weatherSample: { temp: "31°C", condition: "Warm & Sunlit", icon: "☀️", rainChance: "0%" },
    lat: 25.2048,
    lng: 55.2708,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: true
  },
  {
    id: "switzerland",
    name: "Interlaken & Swiss Alps",
    country: "Switzerland",
    region: "International",
    category: "Mountains",
    budgetTier: "Luxury",
    avgDailyCostINR: 18000,
    avgDailyCostUSD: 216,
    rating: 4.9,
    reviews: 2470,
    duration: "5-7 Days",
    bestTime: "June - September (Hiking) & Dec - March (Skiing)",
    description: "Picture-perfect alpine valleys between Lake Thun and Lake Brienz, backed by the towering peaks of Eiger, Mönch, and Jungfrau.",
    highlights: ["Jungfraujoch - Top of Europe", "Lauterbrunnen 72 Waterfalls", "Scenic GoldenPass Train", "Grindelwald First Cliff Walk"],
    attractions: ["Jungfraujoch", "Lauterbrunnen Valley", "Harder Kulm", "Lake Brienz", "Schilthorn"],
    foodMustTry: ["Swiss Cheese Fondue", "Raclette", "Rösti", "Swiss Chocolate Pralines"],
    activities: ["Alpine Paragliding", "Glacier Hikes", "Panoramic Mountain Railways", "Lake Steamboat Cruises"],
    weatherSample: { temp: "15°C", condition: "Fresh Alpine Breeze", icon: "🏔️", rainChance: "20%" },
    lat: 46.6863,
    lng: 7.8632,
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    region: "International",
    category: "Beach",
    budgetTier: "Luxury",
    avgDailyCostINR: 13500,
    avgDailyCostUSD: 162,
    rating: 4.9,
    reviews: 2810,
    duration: "3-5 Days",
    bestTime: "April - November",
    description: "Iconic Cycladic white-washed villages perched high on caldera volcanic cliffs, cobalt blue church domes, and celebrated Aegean Sea sunsets in Oia.",
    highlights: ["Oia Castle Sunset Watching", "Caldera Catamaran Cruise", "Red Beach Volcanic Sand", "Fira to Oia Cliff Hike"],
    attractions: ["Oia Village", "Fira Town", "Akrotiri Archaeological Site", "Perissa Black Sand Beach"],
    foodMustTry: ["Greek Souvlaki", "Fresh Grilled Octopus", "Fava Mezedes", "Tomato Geftedes", "Baklava"],
    activities: ["Sailing Cruises", "Volcano Hiking", "Wine Tasting Tours", "Donkey Trails", "Photography"],
    weatherSample: { temp: "24°C", condition: "Aegean Sunshine", icon: "☀️", rainChance: "5%" },
    lat: 36.3932,
    lng: 25.4615,
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: false
  },
  {
    id: "new-york",
    name: "New York City",
    country: "United States",
    region: "International",
    category: "City",
    budgetTier: "Luxury",
    avgDailyCostINR: 16500,
    avgDailyCostUSD: 198,
    rating: 4.7,
    reviews: 3900,
    duration: "4-6 Days",
    bestTime: "April - June & September - November",
    description: "The city that never sleeps offers towering Empire State vistas, Central Park strolls, Broadway musicals, and an unrivaled global food scene.",
    highlights: ["Central Park Morning Walk", "Broadway Theatre Show", "Top of the Rock Observation", "High Line Park Stroll"],
    attractions: ["Times Square", "Statue of Liberty", "Central Park", "Metropolitan Museum of Art", "Brooklyn Bridge"],
    foodMustTry: ["New York Style Pizza Slice", "Pastrami on Rye", "Bagel with Lox & Cream Cheese", "Cheesecake"],
    activities: ["Broadway Shows", "Museum Exhibitions", "Architecture Boat Tours", "Rooftop Lounge Views"],
    weatherSample: { temp: "21°C", condition: "Sunny & Crisp", icon: "🏙️", rainChance: "15%" },
    lat: 40.7128,
    lng: -74.0060,
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: true
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "International",
    category: "Luxury",
    budgetTier: "Luxury",
    avgDailyCostINR: 19500,
    avgDailyCostUSD: 235,
    rating: 4.9,
    reviews: 2150,
    duration: "4-6 Days",
    bestTime: "November - April",
    description: "An archipelago of coral atolls floating in turquoise Indian Ocean lagoons, renowned for private overwater villas, bioluminescent beaches, and marine life.",
    highlights: ["Overwater Villa Sun Deck", "Snorkeling with Manta Rays", "Underwater Dining Restaurant", "Sandbank Private Picnics"],
    attractions: ["North Malé Atoll", "Baa Atoll Biosphere", "Vaadhoo Island Glowing Beach", "Banana Reef"],
    foodMustTry: ["Mas Huni (Tuna Breakfast)", "Garudhiya (Fish Soup)", "Bis Keemiya", "Coconut Sago"],
    activities: ["Scuba Diving with Sharks", "Dolphin Watching Cruises", "Overwater Spa Treatments", "Jet Skiing"],
    weatherSample: { temp: "30°C", condition: "Tropical Warmth", icon: "🏝️", rainChance: "10%" },
    lat: 3.2028,
    lng: 73.2207,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    trending: true
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    region: "International",
    category: "Culture",
    budgetTier: "Standard",
    avgDailyCostINR: 9800,
    avgDailyCostUSD: 118,
    rating: 4.9,
    reviews: 2760,
    duration: "3-5 Days",
    bestTime: "March - May & October - November",
    description: "Japan's ancient cultural capital featuring thousands of classical Buddhist temples, Zen gardens, traditional wooden machiya houses, and geisha districts.",
    highlights: ["Fushimi Inari Torii Gate Tunnel", "Arashiyama Bamboo Grove", "Kinkaku-ji Golden Pavilion", "Gion Historic Evening Walk"],
    attractions: ["Fushimi Inari-taisha", "Kinkaku-ji", "Kiyomizu-dera", "Arashiyama Bamboo Grove", "Nijo Castle"],
    foodMustTry: ["Kaiseki Multi-course", "Kyoto Udon", "Yudofu (Boiled Tofu)", "Matcha Soft Serve"],
    activities: ["Traditional Tea Ceremony", "Kimono Walking Tour", "Zen Meditation", "Temple Garden Walks"],
    weatherSample: { temp: "17°C", condition: "Clear & Serene", icon: "⛩️", rainChance: "10%" },
    lat: 35.0116,
    lng: 135.7681,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: false
  },
  {
    id: "machu-picchu",
    name: "Machu Picchu",
    country: "Peru",
    region: "International",
    category: "Adventure",
    budgetTier: "Standard",
    avgDailyCostINR: 8500,
    avgDailyCostUSD: 102,
    rating: 4.9,
    reviews: 2310,
    duration: "4-5 Days",
    bestTime: "May - October",
    description: "The mysterious 15th-century Inca citadel perched dramatically on an Andean mountain ridge above the Urubamba River, wrapped in misty cloud forests.",
    highlights: ["Sunrise over Sun Gate", "Huayna Picchu Peak Climb", "Inca Trail 4-Day Trek", "Sacred Valley Exploration"],
    attractions: ["Temple of the Sun", "Intihuatana Stone", "Huayna Picchu", "Ollantaytambo Ruins"],
    foodMustTry: ["Ceviche Clásico", "Lomo Saltado", "Causa Rellena", "Chicha Morada"],
    activities: ["Inca Trail Hiking", "Scenic Vistadome Train", "Archaeology Guided Walks", "Alpaca Encounters"],
    weatherSample: { temp: "16°C", condition: "Misty Mountain Air", icon: "⛰️", rainChance: "30%" },
    lat: -13.1631,
    lng: -72.5450,
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    trending: false
  }
];

// Helper functions for data access
function getDestinationById(id) {
  return DESTINATIONS.find(d => d.id === id);
}

function getFeaturedDestinations() {
  return DESTINATIONS.filter(d => d.featured);
}

function getTrendingDestinations() {
  return DESTINATIONS.filter(d => d.trending);
}

function getAllCategories() {
  return ["All", "Adventure", "Beach", "Mountains", "Culture", "Luxury", "Nature", "City", "Budget"];
}

// Global browser and Node.js environment export
if (typeof window !== 'undefined') {
  window.DESTINATIONS = DESTINATIONS;
  window.getDestinationById = getDestinationById;
  window.getFeaturedDestinations = getFeaturedDestinations;
  window.getTrendingDestinations = getTrendingDestinations;
  window.getAllCategories = getAllCategories;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DESTINATIONS, getDestinationById, getFeaturedDestinations, getTrendingDestinations, getAllCategories };
}
